const data = [
    {
        table: "A",
        no: "048/A/NBP/2021",
        effectiveDate: "2021-03-11",
        rates: [
            { currency: "bat (Tajlandia)", code: "THB", mid: 0.1253 },
            { currency: "dolar amerykański", code: "USD", mid: 3.8287 },
            { currency: "dolar australijski", code: "AUD", mid: 2.9773 },
            { currency: "dolar Hongkongu", code: "HKD", mid: 0.4935 },
            { currency: "dolar kanadyjski", code: "CAD", mid: 3.0434 },
            { currency: "dolar nowozelandzki", code: "NZD", mid: 2.7685 },
            { currency: "dolar singapurski", code: "SGD", mid: 2.8579 },
            { currency: "euro", code: "EUR", mid: 4.5805 },
            { currency: "forint (Węgry)", code: "HUF", mid: 0.012511 },
            { currency: "frank szwajcarski", code: "CHF", mid: 4.1387 },
            { currency: "funt szterling", code: "GBP", mid: 5.3411 },
            { currency: "hrywna (Ukraina)", code: "UAH", mid: 0.138 },
            { currency: "jen (Japonia)", code: "JPY", mid: 0.035296 },
            { currency: "korona czeska", code: "CZK", mid: 0.1746 },
            { currency: "korona duńska", code: "DKK", mid: 0.6159 },
            { currency: "korona islandzka", code: "ISK", mid: 0.029957 },
            { currency: "korona norweska", code: "NOK", mid: 0.4563 },
            { currency: "korona szwedzka", code: "SEK", mid: 0.453 },
            { currency: "kuna (Chorwacja)", code: "HRK", mid: 0.6037 },
            { currency: "lej rumuński", code: "RON", mid: 0.9376 },
            { currency: "lew (Bułgaria)", code: "BGN", mid: 2.3419 },
            { currency: "lira turecka", code: "TRY", mid: 0.5144 },
            { currency: "nowy izraelski szekel", code: "ILS", mid: 1.1587 },
            { currency: "peso chilijskie", code: "CLP", mid: 0.005285 },
            { currency: "peso filipińskie", code: "PHP", mid: 0.0791 },
            { currency: "peso meksykańskie", code: "MXN", mid: 0.1842 },
            {
                currency: "rand (Republika Południowej Afryki)",
                code: "ZAR",
                mid: 0.2562,
            },
            { currency: "real (Brazylia)", code: "BRL", mid: 0.675 },
            { currency: "ringgit (Malezja)", code: "MYR", mid: 0.9321 },
            { currency: "rubel rosyjski", code: "RUB", mid: 0.0521 },
            { currency: "rupia indonezyjska", code: "IDR", mid: 0.00026578 },
            { currency: "rupia indyjska", code: "INR", mid: 0.052704 },
            { currency: "won południowokoreański", code: "KRW", mid: 0.003385 },
            { currency: "yuan renminbi (Chiny)", code: "CNY", mid: 0.5899 },
            { currency: "SDR (MFW)", code: "XDR", mid: 5.496 },
        ],
    },
];

export default data[0];
